// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function LoadConfig():Promise<main.Config>;

export function OpenDirectory():Promise<string>;

export function ReadLogs():Promise<Array<string>>;

export function SaveConfig(arg1:main.Config):Promise<void>;
